### ISSUE TITLE
Errors Since Upgrade to .59.2

### ISSUE THREAD

**Issue by larizzo** [lrogoff/sinope#1]
Have you tried upgrading to HASS 0.59.2? I've been getting errors since I upgraded and I'm no longer getting entities in HASS.

Here's the error log:
```
2017-12-11 19:52:40 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 180, in _step
    result = coro.send(None)
  File "/usr/src/app/homeassistant/helpers/entity_component.py", line 399, in async_process_entity
    new_entity, self, update_before_add=update_before_add
  File "/usr/src/app/homeassistant/helpers/entity_component.py", line 247, in async_add_entity
    yield from entity.async_update_ha_state()
  File "/usr/src/app/homeassistant/helpers/entity.py", line 231, in async_update_ha_state
    attr)
  File "/usr/src/app/homeassistant/helpers/entity.py", line 333, in _attr_setter
    value = getattr(self, name)
  File "/usr/src/app/homeassistant/components/climate/__init__.py", line 736, in supported_features
    raise NotImplementedError()
NotImplementedError
2017-12-11 19:52:40 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 180, in _step
    result = coro.send(None)
  File "/usr/src/app/homeassistant/helpers/entity_component.py", line 399, in async_process_entity
    new_entity, self, update_before_add=update_before_add
  File "/usr/src/app/homeassistant/helpers/entity_component.py", line 247, in async_add_entity
    yield from entity.async_update_ha_state()
  File "/usr/src/app/homeassistant/helpers/entity.py", line 231, in async_update_ha_state
    attr)
  File "/usr/src/app/homeassistant/helpers/entity.py", line 333, in _attr_setter
    value = getattr(self, name)
  File "/usr/src/app/homeassistant/components/climate/__init__.py", line 736, in supported_features
    raise NotImplementedError()
NotImplementedError
```

**Comment by omelettedufromagee** [comment]
I'll upgrade and take a look. Thanks for letting me know.

**Comment by larizzo** [comment]
Did you have a chance to upgrade? Wondering if it's something on my side not working or a change in Home-Assistant. 

Also do you have any code written without the home assistant integration to be able to poll independently?

**Comment by larizzo** [comment]
This is what broke this custom component [10658](https://github.com/home-assistant/home-assistant/pull/10658). I'm trying to figure out what exactly has to change to work but I think a supported_features has to be sent.
